/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import buldingmaintance.*;
import java.util.ArrayList;

/**
 *
 * @author orgershov
 */
public class UserForm extends javax.swing.JFrame {

    User resident;
     ArrayList<Message> messages = new ArrayList<Message>(); 
    public UserForm(Resident resident) {
        initComponents();
     this.resident=resident;
      OnOffComponents(false, false, false, false);
        OnOffPanel(false, false, false, false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMain = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        jpnViewMassege = new javax.swing.JPanel();
        txtViewMassege = new javax.swing.JScrollPane();
        txtShowMessage = new javax.swing.JTextArea();
        jpnPayment = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        txtSum = new javax.swing.JTextField();
        lblSum = new javax.swing.JLabel();
        txtPaymentComannt = new javax.swing.JTextField();
        lblPaymentCommant = new javax.swing.JLabel();
        jpnOrderMaintinace = new javax.swing.JPanel();
        txtSerivceList = new javax.swing.JScrollPane();
        txtServieList = new javax.swing.JTextArea();
        lblServieList = new javax.swing.JLabel();
        lblIdOfService = new javax.swing.JLabel();
        txtEnterIdOfService = new javax.swing.JTextField();
        lblTypeOfService = new javax.swing.JLabel();
        txtEnterTypeOfService = new javax.swing.JTextField();
        btnOrderService = new javax.swing.JButton();
        txtWriteMassege = new javax.swing.JScrollPane();
        txtWrite = new javax.swing.JTextArea();
        lblSendTo = new javax.swing.JLabel();
        txtSendTo = new javax.swing.JTextField();
        btnSendMassege = new javax.swing.JButton();
        btnViewMassege = new javax.swing.JButton();
        btnMakepayment = new javax.swing.JButton();
        btnMakeOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME USER");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jpnMain.setBackground(new java.awt.Color(204, 255, 204));
        jpnMain.setMinimumSize(new java.awt.Dimension(936, 456));
        jpnMain.setLayout(null);

        jpnSendMassege.setBackground(new java.awt.Color(100, 251, 14));
        jpnSendMassege.setOpaque(false);
        jpnSendMassege.setLayout(null);

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSend.setText("send");
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jpnSendMassege.add(btnSend);
        btnSend.setBounds(430, 360, 150, 40);

        jpnViewMassege.setBackground(java.awt.SystemColor.controlLtHighlight);
        jpnViewMassege.setMinimumSize(new java.awt.Dimension(690, 300));
        jpnViewMassege.setOpaque(false);
        jpnViewMassege.setLayout(null);

        txtShowMessage.setColumns(20);
        txtShowMessage.setRows(5);
        txtShowMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtViewMassege.setViewportView(txtShowMessage);

        jpnViewMassege.add(txtViewMassege);
        txtViewMassege.setBounds(70, 80, 510, 260);

        btnShowMesseges.setBackground(new java.awt.Color(255, 255, 255));
        btnShowMesseges.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnShowMesseges.setText("show messeges");
        btnShowMesseges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowMesseges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMessegesActionPerformed(evt);
            }
        });
        jpnViewMassege.add(btnShowMesseges);
        btnShowMesseges.setBounds(50, 20, 170, 40);
        btnShowMesseges.getAccessibleContext().setAccessibleParent(jpnSendMassege);

        jpnPayment.setOpaque(false);
        jpnPayment.setLayout(null);

        btnPay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPay.setText("pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jpnPayment.add(btnPay);
        btnPay.setBounds(70, 320, 110, 40);
        jpnPayment.add(txtSum);
        txtSum.setBounds(70, 130, 150, 30);

        lblSum.setBackground(new java.awt.Color(102, 204, 255));
        lblSum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSum.setText("enter sum");
        jpnPayment.add(lblSum);
        lblSum.setBounds(70, 100, 130, 22);
        jpnPayment.add(txtPaymentComannt);
        txtPaymentComannt.setBounds(70, 190, 310, 110);

        lblPaymentCommant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPaymentCommant.setText("Comant");
        jpnPayment.add(lblPaymentCommant);
        lblPaymentCommant.setBounds(70, 170, 140, 22);

        jpnOrderMaintinace.setOpaque(false);
        jpnOrderMaintinace.setLayout(null);

        txtServieList.setColumns(20);
        txtServieList.setRows(5);
        txtSerivceList.setViewportView(txtServieList);

        jpnOrderMaintinace.add(txtSerivceList);
        txtSerivceList.setBounds(30, 80, 390, 250);

        lblServieList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblServieList.setText("list of services");
        jpnOrderMaintinace.add(lblServieList);
        lblServieList.setBounds(40, 40, 130, 22);

        lblIdOfService.setText("chosen service id");
        jpnOrderMaintinace.add(lblIdOfService);
        lblIdOfService.setBounds(30, 360, 110, 30);
        jpnOrderMaintinace.add(txtEnterIdOfService);
        txtEnterIdOfService.setBounds(30, 400, 110, 22);

        lblTypeOfService.setText("type of service");
        jpnOrderMaintinace.add(lblTypeOfService);
        lblTypeOfService.setBounds(190, 370, 90, 16);
        jpnOrderMaintinace.add(txtEnterTypeOfService);
        txtEnterTypeOfService.setBounds(180, 400, 100, 22);

        btnOrderService.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrderService.setText("order");
        btnOrderService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrderService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderServiceActionPerformed(evt);
            }
        });
        jpnOrderMaintinace.add(btnOrderService);
        btnOrderService.setBounds(360, 375, 120, 40);

        jpnPayment.add(jpnOrderMaintinace);
        jpnOrderMaintinace.setBounds(0, 0, 650, 490);

        jpnViewMassege.add(jpnPayment);
        jpnPayment.setBounds(0, 0, 640, 480);

        txtWrite.setColumns(20);
        txtWrite.setRows(5);
        txtWriteMassege.setViewportView(txtWrite);

        jpnViewMassege.add(txtWriteMassege);
        txtWriteMassege.setBounds(70, 80, 510, 250);

        jpnSendMassege.add(jpnViewMassege);
        jpnViewMassege.setBounds(0, 0, 660, 470);
        jpnViewMassege.getAccessibleContext().setAccessibleParent(jpnMain);

        lblSendTo.setText("send to");
        jpnSendMassege.add(lblSendTo);
        lblSendTo.setBounds(80, 56, 70, 20);
        jpnSendMassege.add(txtSendTo);
        txtSendTo.setBounds(130, 60, 80, 20);

        jpnMain.add(jpnSendMassege);
        jpnSendMassege.setBounds(290, 0, 670, 460);

        btnSendMassege.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSendMassege.setText("send massege");
        btnSendMassege.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSendMassege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMassegeActionPerformed(evt);
            }
        });
        jpnMain.add(btnSendMassege);
        btnSendMassege.setBounds(50, 60, 190, 50);

        btnViewMassege.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewMassege.setText("view massege");
        btnViewMassege.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewMassege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMassegeActionPerformed(evt);
            }
        });
        jpnMain.add(btnViewMassege);
        btnViewMassege.setBounds(50, 140, 190, 50);

        btnMakepayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMakepayment.setText("make patment");
        btnMakepayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMakepayment.setOpaque(false);
        btnMakepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakepaymentActionPerformed(evt);
            }
        });
        jpnMain.add(btnMakepayment);
        btnMakepayment.setBounds(50, 220, 190, 50);

        btnMakeOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMakeOrder.setText("order maintainace");
        btnMakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeOrderActionPerformed(evt);
            }
        });
        jpnMain.add(btnMakeOrder);
        btnMakeOrder.setBounds(50, 300, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/UFBackgrund.png"))); // NOI18N
        jpnMain.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 630);

        getContentPane().add(jpnMain);

        setBounds(250, 250, 957, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMassegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMassegeActionPerformed

        OnOffComponents(true, false, false, false);
        OnOffPanel(true, false, false, false);
    }//GEN-LAST:event_btnSendMassegeActionPerformed

    private void btnViewMassegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMassegeActionPerformed
       
       OnOffComponents(false, true, false, false);
        OnOffPanel(true, true, false, false);
       
    }//GEN-LAST:event_btnViewMassegeActionPerformed

    /**
     * show my messages
     * @param evt 
     */
    private void btnShowMessegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMessegesActionPerformed
    
    }//GEN-LAST:event_btnShowMessegesActionPerformed
/**
 * send my message
 * @param evt 
 */
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
    String content=txtWrite.getText();
    String to=txtSendTo.getText();
    Message message=new Message(content,resident.getUserName(),to);
    resident.SendMessage(message);
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnMakepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakepaymentActionPerformed
        OnOffComponents(false, false, true, false);
        OnOffPanel(true, true, true, false);
    }//GEN-LAST:event_btnMakepaymentActionPerformed

    private void btnMakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeOrderActionPerformed
         OnOffComponents(false, false, false, true);
        OnOffPanel(true, true, true, true);
    }//GEN-LAST:event_btnMakeOrderActionPerformed
/**
 * make my payment
 * @param evt 
 */
    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
       int sum=Integer.parseInt(txtSum.getText());
        String commant=txtPaymentComannt.getText();
        Payment pay =new Payment(resident.getUserName(),"Admin",commant,sum);
    }//GEN-LAST:event_btnPayActionPerformed
/**
 * order a servie
 * @param evt 
 */
    private void btnOrderServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderServiceActionPerformed
       
       
    }//GEN-LAST:event_btnOrderServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public void OnOffPanel(boolean sendMessage,boolean viewMessage ,boolean payment,boolean order) {
        jpnSendMassege.setVisible(sendMessage); 
        jpnViewMassege.setVisible(viewMessage);    
        jpnPayment.setVisible(payment);
        jpnOrderMaintinace.setVisible(order);
              
    }
    public void OnOffComponents(boolean sendMessage,boolean viewMessage ,boolean payment,boolean order) {
       btnSend.setVisible(sendMessage);
       txtWriteMassege.setVisible(sendMessage);
       txtWrite.setVisible(sendMessage);
       txtSendTo.setVisible(sendMessage);
       lblSendTo.setVisible(sendMessage);        
       
       btnShowMesseges.setVisible(viewMessage);
       txtViewMassege.setVisible(viewMessage);
       
       btnPay.setVisible(payment);
       txtSum.setVisible(payment);
       lblSum.setVisible(payment);
       lblPaymentCommant.setVisible(payment);
       txtPaymentComannt.setVisible(payment);
       
       txtServieList.setVisible(order);
       lblServieList.setVisible(order);
       lblTypeOfService.setVisible(order);
       txtEnterIdOfService.setVisible(order);
       txtEnterTypeOfService.setVisible(order);
       btnOrderService.setVisible(order);
       
              
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeOrder;
    private javax.swing.JButton btnMakepayment;
    private javax.swing.JButton btnOrderService;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendMassege;
    private final javax.swing.JButton btnShowMesseges = new javax.swing.JButton();
    private javax.swing.JButton btnViewMassege;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnOrderMaintinace;
    private javax.swing.JPanel jpnPayment;
    private final javax.swing.JPanel jpnSendMassege = new javax.swing.JPanel();
    private javax.swing.JPanel jpnViewMassege;
    private javax.swing.JLabel lblIdOfService;
    private javax.swing.JLabel lblPaymentCommant;
    private javax.swing.JLabel lblSendTo;
    private javax.swing.JLabel lblServieList;
    private javax.swing.JLabel lblSum;
    private javax.swing.JLabel lblTypeOfService;
    private javax.swing.JTextField txtEnterIdOfService;
    private javax.swing.JTextField txtEnterTypeOfService;
    private javax.swing.JTextField txtPaymentComannt;
    private javax.swing.JTextField txtSendTo;
    private javax.swing.JScrollPane txtSerivceList;
    private javax.swing.JTextArea txtServieList;
    private javax.swing.JTextArea txtShowMessage;
    private javax.swing.JTextField txtSum;
    private javax.swing.JScrollPane txtViewMassege;
    private javax.swing.JTextArea txtWrite;
    private javax.swing.JScrollPane txtWriteMassege;
    // End of variables declaration//GEN-END:variables
}
